### ISSUE TITLE
Unable to create chart from dialog template in memory

### ISSUE THREAD

**Issue by schnufff** [mity/mctrl#35]
Hi Mity,
at first, thanks for your work: Exactly what I was looking for!

When creating the chart dialog using DLGTEMPLATE and DLGITEMTEMPLATE (without EX), all controls except the chart are created. I guess its related to the WindowClass "mCtrl.chart".
Using a resource file, everything works.

Is this the right place to discuss the topic with you?

All the best
schnufff

**Comment by neduddgi** [comment]
nchar should be incremented:
lpw += nchar +1;
