### ISSUE TITLE
Crash in Visual Studio 2010 - Release

### ISSUE THREAD

**Issue by joose2015** [mity/mctrl#39]
Version: 0.10 - Release - 32/64bits
SO: Windows 8.1
Chars: Multibyte
Compiler: Visual Studio 2010 SDK 7.1
![unhandledexception](https://cloud.githubusercontent.com/assets/11507333/10525139/b0ac1644-7348-11e5-8e13-c9dc10d8e61e.png)
https://drive.google.com/file/d/0B0iV68ilFYBhVkZPb1hwdEZFdUU/view?usp=sharing

When running the application in release versions in Visual Studio 2010 (v100 or SDK 7.1 32/64 bit) error 0xC0000005: Access violation, apparently there is a problem in the initialization and termination functions. Deputy screenshot project file, I tried it with chart_control but all examples show the same error does not occur in debug versions.

**Comment by mity** [comment]
Ok, I've just installed MSVC 2010 Express (so I can play only with the 32-bit build). I can see that in the release build, import table of the target `CHART_01.EXE` is somehow broken.

This is from the debug build (which looks and runs ok for me):
```
Import Table:
  mCtrl.dll
    Import Address Table:               0x0000C740
    Import Name Table:                  0x0000C3C8
    Time Date Stamp:                    0x00000000
    Index of first forwarder reference: 0x00000000

         11   mcChart_Initialize
         20   mcDialogBoxParamA

  USER32.dll
    Import Address Table:               0x0000C6B8
    Import Name Table:                  0x0000C340
    Time Date Stamp:                    0x00000000
    Index of first forwarder reference: 0x00000000

        722   SetWindowTextA
        635   SendMessageA
... (shortened)
```

And this from the Release build:
```
Import Table:
  mCtrl.dll
    Import Address Table:               0x00002170
    Import Name Table:                  0x00002678
    Time Date Stamp:                    0x00000000
    Index of first forwarder reference: 0x00000000


  USER32.dll
    Import Address Table:               0x00002148
    Import Name Table:                  0x00002650
    Time Date Stamp:                    0x00000000
    Index of first forwarder reference: 0x00000000

        635   SendMessageA
        297   GetDlgItem
... (shortened)
```

See? Somehow  the symbols `mcChart_Initialize` and `mcDialogBoxParamA` from `MCTRL.DLL` are not imported anymore into the `.EXE`.

After some playing with project options, I can see that somehow the linker command line option `/OPT:REF` (or in MSVC GUI, the option `CHART_01 project >> Properties >> Optimization >> References` translates to it) is what matters here. When enabled, it breaks the import table of the outputed `CHART_01.EXE`.

I have no idea why it is this way. I'm no expert on what exactly that option does and how it works, or why it interacts badly with `MCTRL.LIB`. I'll try to dig some more info but it can take some time.

For now the workaround is to simply disable that optimization option and rebuild.

**Comment by mity** [comment]
It's some incompatibility between import libs as produced by MSVC and by `gcc`. 

For some historic reasons (full MSVC not available for free), the import mCtrl libs for MSVC are just renamed import lib produced by `gcc` (`libmctrl.a`). I'll change this to the next release.

So the alternative workaround is to use import mctrl import libs as created by MSVC. Either rebuild MCTRL.DLL with Visual Studio (but 2010 will likely not work, you probably need 2013 or 2015), or you may download the libs from here:
* https://ci.appveyor.com/project/mity/mctrl/build/job/ecr6j6by80cm2en1/artifacts
* https://ci.appveyor.com/project/mity/mctrl/build/job/s8g9d33u5fjmpymf/artifacts

(Just replace `MCTRL.LIB` with in the 0.10.0 release package with those from here.)

**Comment by joose2015** [comment]
Problems were solved. 2 alternatives work well, I'll stay with mctrl.lib and mctrl.dll new compilation in 32/64 bits.

Thanks for the quick reply.

**Comment by mity** [comment]
Note version 0.11.0 is out, where this should be fixed.
