### ISSUE TITLE
Not respond to NM_RCLICK and NM_RDBLCLK

### ISSUE THREAD

**Issue by joose2015** [mity/mctrl#40]
Version: 0.10 - Release - 32/64bits
SO: Windows 8.1
Chars: Multibyte
Compiler: CodeBlocks 13.12 GCC 4.7.1

https://drive.google.com/file/d/0B0iV68ilFYBhS0E4LXd0bzJuZm8/view?usp=sharing

The mGrid replaces notifications NM_RCLICK by NM_CLICK  and NM_RDBLCLK by NM_DBLCLK.

**Comment by mity** [comment]
Fixed. Thanks for the report.
