### ISSUE TITLE
TreeList: Select item in a non MC_TLS_MULTISELECT control

### ISSUE THREAD

**Issue by Bugzero71** [mity/mctrl#42]
First of all thanks for this great control library.

I'm using TreeList control without enabling multiselection. When I try to send a MC_TLM_SETITEMW to select an item manually I get an assertion caused by line 1734 in file treelist.c (release-0.11.1):

    MC_ASSERT(tl->style & MC_TLS_MULTISELECT);

The control works correctly instead. Is this the best way to select an item from source? 

Thanks

Jordi L.

**Comment by mity** [comment]
Yes, it is definitely the right way how to change the selection from a program. 

However it is clearly broken. I'll take a look at it over the weekend and likely release a hotfix version as this seems as a quite serious issue and there is no easy workaround. 

Thanks for reporting it.

**Comment by Bugzero71** [comment]
Thanks for your answer.

Now, I'm using DLL Release version as it works perfectly as expected. Probably this line is not needed as I can't detect any other issues.

**Comment by mity** [comment]
It may cause glitches with the 0.11.1. Given the nature of the bug, it likely can result in having more then one item selected as if having the style `MC_TLS_MULTISELECT` enabled.

**Comment by mity** [comment]
@Bugzero71: Could you please test it with your code? Feel free to reopen if it does not fix it.

(You may pick up the binaries at https://ci.appveyor.com/project/mity/mctrl/branch/master once the build finishes if you don't want to build manually.)

**Comment by Bugzero71** [comment]
@mity: Thank you very much with this hotfix.

I've updated my HEAD to '213c2dc' and compiled both configurations (Debug & Release). It works fine now.

I'll be using your great library and try to help you finding bugs or solving them if I can.
