### ISSUE TITLE
[TreeList] Exception on MC_TLN_GETSUBDISPINFO

### ISSUE THREAD

**Issue by Bugzero71** [mity/mctrl#46]
Martin, TreeList is throwing an exception when a subitem must be defined and it's not.
I'm using MC_LPSTR_TEXTCALLBACKW to define a subitem text and an assertion is thrown if value in DispInfo struct pszText is not defined. In fact it is not previously defined as nullptr.

It's easy to correct. Only add in treelist.c, line 403:

```cpp
	info.subitem.pszText = NULL;			// Prevent from exception
```
That's all

**Comment by Bugzero71** [comment]
Martin, I've got some new exceptions in treelist_free_subdispinfo(...). This function is freeing a pointer which I was assuming that it should be controlled by application. This is not the way Grid is working.

My code in MC_TLN_GETDISPINFOW is like this:

```cpp
  MC_NMTLSUBDISPINFOW* lpDispInfo = (MC_NMTLSUBDISPINFOW*)pNotifyStruct;

  if (lpDispInfo != nullptr
     && m_pMemory_ != nullptr)
  {
    ELOGIC::label_id_t label_id = GET_LABID(lpDispInfo->lItemParam);

    if (label_id != ELOGIC::INVALID_LABEL_ID)
    {
       MC_TLSUBITEMW& subitem = lpDispInfo->subitem;

       wsprintf(m_szTempBuffer_, L"%ld", m_pMemory_->GetLabelValue(label_id));
       subitem.pszText = m_szTempBuffer_;
    }
  }

  *pResult = TRUE;
```

**Comment by mity** [comment]
I committed some fixes. 

Please next time rather open new issue for each bug. If you include multiple into single thread, I cannot reasonable refer to single bug from a commit, and if there is a longer discussion for multiple bugs in single report it's messy to read.

**Comment by Bugzero71** [comment]
OK, Martin no exception is thrown at this moment and values are updated as expected.
