### ISSUE TITLE
Focus problem in Grid Control

### ISSUE THREAD

**Issue by Bugzero71** [mity/mctrl#47]
Martin, when using the Grid control full Win32 application, where other controls and views are displayed, I need to catch NM_CLICK notify message sent from the control on my parent window, to call `SetFocus(hGridCtrl)` and set correctly the Focus. 

It seems WM_LBUTTONDOWN does not set focus inside the control. I've looked at Tree List control and this is done correctly.

**Comment by mity** [comment]
Done.
