### ISSUE TITLE
Notification Messages from Grid control

### ISSUE THREAD

**Issue by Bugzero71** [mity/mctrl#48]
As I read in file grid.h Notification Messages ``MC_GN_GETDISPINFOW`` and ``MC_GN_GETDISPINFOA`` should send control id in ``wParam`` parameter (lines 1043 and 1066).

In file grid.c, line 648 a 0 value is passed and should be ``info.hdr.idFrom`` 

```cpp
MC_SEND(grid->notify_win, WM_NOTIFY, 0, &info);
```

**Comment by mity** [comment]
Thanks. Fixed.
