### ISSUE TITLE
Grid, color of divisions and new feature edit crash

### ISSUE THREAD

**Issue by joose2015** [mity/mctrl#54]
Hello, I wanted to ask how to change the color of the divisions, in some screens of laptop and monitors is not well distinguished, it would be nice to be able to darken the color. Another problem is to edit the cells, sometimes works well and sometimes the program hangs. I apologize for my bad English. Thank you.

**Comment by mity** [comment]
Next time please report only one thing per issue request.

I created #55 and #56 to handle the issues independently.

**Comment by mity** [comment]
@joose2015 Please consider subscribing to those two issues so you get informed if there is some progres with them.
