### ISSUE TITLE
Visual studio

### ISSUE THREAD

**Issue by devulder** [mity/mctrl#57]
Hi,
It's great for have visual studio for mCtrl

Use Cmake not easy for noob ;)

**Comment by mity** [comment]
> Use Cmake not easy for noob ;)

Well, maybe. But having native project files for every IDE would be huge maintenance burden. Even for just MSVC, people use plethora of MSVC versions.

And given that [MSVC 2017 should support CMake directly](https://blogs.msdn.microsoft.com/vcblog/2016/10/05/cmake-support-in-visual-studio/), it should become palatable for noobs as well.

But it's true I should at least try it and if it really works, then I should update the README.md file accordingly. I take a look at it.

**Comment by mity** [comment]
It works in MSVC 20176 nicely, as described in updated README.md

**Comment by devulder** [comment]
Work well!
Thanks,
