### ISSUE TITLE
access violation on html_destroy

### ISSUE THREAD

**Issue by AlessioR** [mity/mctrl#58]
Hi,

on html_destroy function at row 1717 after

IOleObject_SetClientSite(html->ole_obj, NULL);

html pointer is no longer valid 'cause html_release is called from client_site_Release
so next line cause an access violation:

 CoDisconnectObject((IUnknown*) html->ole_obj, 0);

**Comment by mity** [comment]
Hello. 

Thanks for the report. 

However are you reporting this just after reading the source, or can you really reproduce the issue in runtime?

My understanding of the code is as follows: The pointer `html` should still be valid as its really destructed only when `html_Release()` drops the reference count to zero. The control itself holds one reference till `html_ncdestroy()` which is always called after `html_destroy()` containing the line 1717.

(That said, there of course may be some bug with the reference counting, but my testing does not indicate so.)

**Comment by AlessioR** [comment]
I can reproduce it on runtime but I've added some stuff to the code ( keyboard key processing and call c function from js)
I need to check better my code, sorry for this.

Are you working to extend html control functionality ?
Are you aware about "<meta http-equiv="X-UA-Compatible" content="IE=edge">" html tag ?
It seems to place IE into installed IE rendering mode without change registry settings. I've tested it with some html5 widgets.

**Comment by mity** [comment]
> I can reproduce it on runtime but I've added some stuff to the code ( keyboard key processing and call c function from js)
I need to check better my code, sorry for this.

Well, I don't say there cannot be bug in mCtrl. But if it is , it would be very handful if you could eventually provide a code which can reproduce it.

> Are you working to extend html control functionality ?

Not at this time.

> Are you aware about "" html tag ? It seems to place IE into installed IE rendering mode without change registry settings. I've tested it with some html5 widgets.

No. Any link/documentation about it?

**Comment by AlessioR** [comment]
I'll check my code to see if is my fault.

I'm referring to this html tag:
meta http-equiv="X-UA-Compatible" content="IE=edge"
github do not like html strings in comments.

Some info here :
https://msdn.microsoft.com/en-us/library/jj676915(v=vs.85).aspx
and
https://stackoverflow.com/questions/6771258/what-does-meta-http-equiv-x-ua-compatible-content-ie-edge-do
The user-agent is still reported as IE7 but the page will be correctly rendered.

I've attached a tested example.
[html5_test.txt](https://github.com/mity/mctrl/files/1152254/html5_test.txt)

**Comment by AlessioR** [comment]
Sorry, it was my fault.
I've messed up thing with OLE stuff.
Thank you for your time, 

Alessio

**Comment by mity** [comment]
No problem. I'm glad it has been explained as debugging this particular kind of bug could be nightmare ;-)
