### ISSUE TITLE
I keep getting this error 'LPCDLGTEMPLATEA' has not been declared

### ISSUE THREAD

**Issue by Jacksiro** [mity/mctrl#67]
**mCtrl 0.11.4:**
I see this error with both 32-bit or 64-bit build in either Release or Debug configuration.

**Windows 32/64 bit:**

**mctrl\dialog.h|163|error: 'LPCDLGTEMPLATEA' has not been declared:**
I have tried to build one of your examples of the **example button** on my own but I can't seem to get around the error. I first used falcon c++ ide which i have used for quite a long time now then switched to code blocks ide where I have continued to experience the error. I added the required libraries, dll and offcourse mctrl in my project but noting seems to work since I cant go past that error.

**Comment by mity** [comment]
`LPCDLGTEMPLATEA` is type from Windows SDK, used by e.g. [`CreateDialogIndirectParamA()`](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-createdialogindirectparama). The type should be defined in `<winuser.h>` which is included into `"mctrl/dialog.h"` through `<windows.h>`.

For example, `<winuser.h>` in Windows SDK used by MSVC 2017 does it as follows:

``` C
#pragma region Application Family
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)

typedef CONST DLGTEMPLATE *LPCDLGTEMPLATEA;
typedef CONST DLGTEMPLATE *LPCDLGTEMPLATEW;
#ifdef UNICODE
typedef LPCDLGTEMPLATEW LPCDLGTEMPLATE;
#else
typedef LPCDLGTEMPLATEA LPCDLGTEMPLATE;
#endif // UNICODE

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP) */
```

I do not know much about CodeBlocks and I do not even know anything about Falcon. 

Do they use headers from standard Microsoft SDK? Or do they use their own Windows headers? If the former, is it possible that the test `#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)` fails with your compiler? Perhaps you must somehow tell it you are building desktop application to pass the check. If it uses its own set of Windows headers, does their version of `<winuser.h>` provide the type (or the function `CreateDialogIndirectParamA()` which is supposed to use it)?

**Comment by JackSiro** [comment]
Okay as at now I am not using Falcon because it uses old mingw version and changing it to the current has not been successful. I have resorted to using Code blocks because some examples actually compiled except for the example button.
I have the latest version of mingw installed by the way. I am hoping I can compile with using GCC and not MSVC such that my program is able to run without prompting the user to install additional programs like .NET.
I am hoping the headers are standard but some lines may be missing or are different.

like this line could not compile 
`hwndStatus = CreateWindow(STATUSCLASSNAME, NULL, WS_CHILD | WS_VISIBLE | SBARS_SIZEGRIP,
                                    0, 0, 0, 0, hwnd, (HMENU) ID_STATUS, hInst, NULL);`

till I changed it to:
`hwndStatus = CreateWindow(STATUSCUASSNAME, NULL, WS_CHILD | WS_VISIBLE | SBARS_SIZEGRIP,
                                    0, 0, 0, 0, hwnd, (HMENU) ID_STATUS, hInst, NULL);`

**Comment by mity** [comment]
Is it mingw or mingw-w64? I use mingw-w64 and gcc without any problem.

**Comment by Jacksiro** [comment]
Oh I see, I was using mingw and not mingw-w64. Please forgive my ignorance for assuming things. I was thinking mingw-w64 is targeting 64-bit environments only. Am still newbie in this stuff and now you just made me aware of something I was not even thinking of for a long time. You see I have been trying this for a whole year without success and it is only today that I got the guts of opening an issue after seeing how you manage issues on your repo. Thanks a million times @mity and feel free to close this issue. If I get another I will certainly open knowing there is someone committed to help on the other end.

**Comment by mity** [comment]
mingw-w64 is fork of mingw created when mingw failed to deliver capability to build 64-bit binaries for years, but it is still fully capable to build 32-bit as well. Maybe that's the reason for the ugly name. AFAIK, most people eventually switched to mingw-w64. 

mingw-w64 has also always been more responsive to patches adding missing things in the Windows headers so they are much more complete.
