### ISSUE TITLE
[Feature Request] Static build

### ISSUE THREAD

**Issue by namazso** [mity/mctrl#75]
Would it be possible to support building as a static library?
I did [some dirty patches](https://github.com/namazso/mctrl-static/commit/c017d0e4509e65f8fd37a0528d4813108d9bab09) to get it work as a static library, but I broke some controls (that I don't need) with the changes. It would be great to have it supported out of the box. To keep the binary sizes down a way to control the modules compiled would also be great

**Comment by mity** [comment]
I agree it would be a nice feature to have. There was a demand for that in the past and I know about at least two teams/projects that did the same, but also in a dirty way.

The main (and likely the only one) technical issue is the resources embedded in mctrl.dll. I really don't know how to reasonably deal with that though.

**Comment by namazso** [comment]
I think as a first step just disabling the controls using them (button, expand, grid) would work.
For a long time solution, I'd have a parameter for resource ids in the initializer for each module, and have an inline wrapper function (withe the name of the current init function for compatibility) in the header that just passes the resources defines, so you can just simply add the resources to your project and have it work. Options to remove modules, or these inline wrappers should be in place too, so you arent forced to always add all the resources.

**Comment by namazso** [comment]
![image](https://user-images.githubusercontent.com/8676443/77600029-e888fc80-6f06-11ea-94c4-828321a62bbc.png)
something like this

**Comment by mity** [comment]
Humm. That's an interesting idea.

I have a little problem with scalability of that solution (too much conditional compilation; API change when a new resource is added/removed etc.) **but** maybe it could work as follows:

1. There would be one global variable, e.g. `int resource_id_base`.
2. For static build, the core initialization function (i.e. what's in the case of DLL called from `DllMain(DLL_PROCESS_ATTACH)`) would take one parameter which would set this variable.

Unlike your suggestion, this would require one thing from the application linking with the static lib: To keep the same offsets of the resources from some arbitrary base number, which would allow to move the resource into a range where it does not collide with the app's own resources.

(We could maybe simplify that for app developers by providing a helper header he could use to define the resource IDs starting at a base define by some preprocessor macro.)

Would something like this work for you?

**Comment by namazso** [comment]
I don't think so. My app doesn't use any controls that use resources, so I'd prefer a way to avoid having the unnecessary resources packed. This was the primary reason why I suggested moving the now global resources to control level

**Comment by namazso** [comment]
As for the API breakage on new resource that you mentioned: I don't think that's a problem. We need the user to add the new resource to their project anyways, so a sort of "API breakage" happens anyways.

**Comment by mity** [comment]
> I don't think so. My app doesn't use any controls that use resources, so I'd prefer a way to avoid having the unnecessary resources packed. This was the primary reason why I suggested moving the now global resources to control level.

It would **not** require you to do that. You could provide any base number (e.g. zero) and no resource in your app as long as no control needs it because no one would call `LoadResource(resource_id_base + resource_id)`.

If/when you later start using other control which needs resources, you would just add those resources needed by that particular control. You would only have to keep the resource id of such resources so that `resource_id_base + resource_id` identifies it. 

`resource_id_base` would be under your control so you could anytime place all the resources into another range if needed e.g. when refactoring the resources in your app.

> As for the API breakage on new resource that you mentioned: I don't think that's a problem. We need the user to add the new resource to their project anyways, so a sort of "API breakage" happens anyways.

Yes, but from mctrl's point of view it means a boilerplate code per every single resource. Ugh.

**Comment by namazso** [comment]
> It would **not** require you to do that. You could provide any base number (e.g. zero) and no resource in your app as long as no control needs it because no one would call `LoadResource(resource_id_base + resource_id)`.

https://github.com/namazso/mctrl-static/commit/c017d0e4509e65f8fd37a0528d4813108d9bab09#diff-4a37aac5c8f7e438572f91c0ed94cfcbL747-L755

these lines are *always* ran on mctrl initialization. Do you plan to move them over to the button control's initialization, since that's the only place they're used?

**Comment by mity** [comment]
> these lines are always ran on mctrl initialization.

At the time I expected some pictograms would be eventually reused by more controls but it has never happened. So yes, we may move it to the button initialization.

If in the future we have another control which would need to reuse it, we could do something clever then, e.g. a helper module shared by both such controls, which would be responsible only for loading the shared resource.

**Comment by namazso** [comment]
then this solution sounds fine (for me atleast).

Also, after some testing it seems like current code allows the linker to strip the unused controls entirely, so the per-control disabling is not really necessary either

**Comment by namazso** [comment]
Thanks for this!

btw, you might want to briefly mention the license in the static build docs, since staticly linking to mctrl means everything else must at very least be LGPL. My software is GPL so this isn't really affecting me, but I think it might affect others.
