### ISSUE TITLE
[Bug] MC_GM_SETSELECTION with NULL lParam crash

### ISSUE THREAD

**Issue by matwachich** [mity/mctrl#83]
**mCtrl version:**
0.11.5 both x86 and x64

**Windows version:**
Windows 10 x64

**Describe the bug:**
Setting lParam = NULL when calling MC_GM_SETSELECTION crashes the application
 
**Is the issue related to building?**
No

**Attachments:**
Documentation of MC_GM_SETSELECTION states:
[in]	lParam	(MC_GSELECTION*) Pointer to structure describing the selection, **or NULL to reset selection.**

But when doing this, the application crashes.

I took a look at source code, and I see no NULL pointer check in
```
static int
grid_set_selection(grid_t* grid, MC_GSELECTION* gsel)
```

**Comment by mity** [comment]
Ack. Looking at it.
