### ISSUE TITLE
[Clarification Needed] About  MC_CHM_INSERTDATASET

### ISSUE THREAD

**Issue by matwachich** [mity/mctrl#84]
Juste a simple (silly?) question about MC_CHM_INSERTDATASET:

What is the interest of passing index of the new dataset to MC_CHM_INSERTDATASET if the index is returned by the message call, and you can not choose any index you want (I mean the dataset indexes are enforced in the range [0, dataSetCount[ (just like a C array)).

I think the parameter should be deleted. It has absolutly no utility in this function.

Here is some pseudo-code:
```
// this is permitted, but has no utility, and can lead to misunderstanding the function
for (int i = 10; i < 20; i++) {
    SendMessage(hWnd, MC_CHM_INSERTDATASET, i, &dataSet);
}

// here, by reading the doc, I think I create a chart with 10 data sets, numbered from 10 to 19.
// but the result is datasets numbered from 0 to 9.
// I think there is no problem numbering the data sets like C arrays, but the doc and the fact that the message accepts this (useless?) parameter can lead to misunderstanding.

// another example:
// let's say that I know that the parameter (wParam: dataset ID) is useless, and i call the function with always 0 parameter.
for (int i = 0; i < 10; i++) {
    printf("dataset N°%d ID = %d\n", i, SendMessage(hWnd, MC_CHM_INSERTDATASET, 0, &dataSet));
}

// the function works well, 10 datasets are added to the chart, but the message returns always 0 for all datasets!
// output
// dataset N°0 ID = 0
// dataset N°1 ID = 0
// dataset N°2 ID = 0
// ...
// dataset N°9 ID = 0
```

**Comment by mity** [comment]
The parameter allows you to insert later a data set to any position in the internal array. The order of the array determines some visual aspects like e.g. the order of the items in the chart legend or the order of segments in the pie chart.

We also return the index for the sake of consistency as many standard win32 controls behave the same when adding items or other stuff into them, for example [`LVM_INSERTCOLUMN`](https://docs.microsoft.com/en-us/windows/win32/controls/lvm-insertcolumn).
