### ISSUE TITLE
[Bug] [mditab] After enabling the dwm extended frame, the window cannot be resized from a specific area

### ISSUE THREAD

**Issue by codehz** [mity/mctrl#86]
**mCtrl version:**
0.11.5 from http://www.mctrl.org/download/0.11.5/mCtrl-0.11.5-bin.zip

**Windows version:**
windows 10 2004 (20262.1010)

**Describe the bug:**
step:
 1. Run example-mditab-dwm.exe
 2. Move the mouse to the left (or right) of the tab control area of the window (outside the window "visible" border, on windows10)
 3. Try to resize window

expected: resizing
actual: moving

**Attachments:**

![image](https://user-images.githubusercontent.com/13158903/100586907-d62f5000-332a-11eb-8a64-1ed176e33e63.png)

**Comment by mity** [comment]
Fixed. Thanks for reporting.
