### ISSUE TITLE
[Bug] Wrong width for midtab item if no icon (always overflow)

### ISSUE THREAD

**Issue by codehz** [mity/mctrl#88]
**mCtrl version:**
(Tested on 0.11.5 and master)

**Windows version:**
Windows 10 x64 20270

**Describe the bug:**
The tab width should be fit the text, so the overflow `...` should never appear (if short than max width)
 
**Is the issue related to building?**
NO

**Attachments:**
![image](https://user-images.githubusercontent.com/13158903/101624535-037bac80-3a55-11eb-9a71-ce33cfa76be0.png)
![image](https://user-images.githubusercontent.com/13158903/101624613-21e1a800-3a55-11eb-8ceb-871e8e44b8eb.png)

PS: DPI is 125%

**Comment by codehz** [comment]
![image](https://user-images.githubusercontent.com/13158903/101628203-69b6fe00-3a5a-11eb-9430-eb1617e4f673.png)

https://github.com/mity/mctrl/blob/master/src/mditab.c#L373

if I change to MDITAB_ITEM_PADDING * 2, it seems workings again...
But I'm not sure..

**Comment by mity** [comment]
There was indeed a bad calculation of the ideal width when there are no icons.

I tried to fix in db87aecc14ab912f681ef7c5b22f939e53957b6a but I don't have a time to test that right now.

Also note that improving a DPI support is on my to do list. There may be some bugs around it, especially in the case when the application uses PerMonitorV2 and the DPI is changed in the lifetime of the controls.

**Comment by codehz** [comment]
I tested db87aec , it works. should I close this issue or leave it until dpi problem fixed?

**Comment by mity** [comment]
Closing, the DPI support is not related to this.
